ratio-res: ":ratio-resources" {
  "Shared resources"
  "strings and drawables"
}
ratio-base: ":ratio-base" {
  "Code shared everywhere"
}
ratio-data: ":ratio-data" {
  "Data Layer" {
    style {
      fill: blue
      font-color: white
    }
  }
  "CRUD: Repositories & DataSources"
}
ratio-domain: ":ratio-domain" {
  "Domain Layer" {
    style {
      fill: blue
      font-color: white
    }
  }
  "Business logic & rules"
}
ratio-common-ui: ":ratio-common-ui" {
  "UI components bundled with domain logic"
}
ratio-nav: ":ratio-navigation" {
  "Screen destinations"
  "Navigation logic"
}
ratio-design: ":ratio-design" {
  "Ratio's design system"
}
screens: ":screen/feature" {
  "UI Layer" {
    style {
      fill: blue
      font-color: white
    }
  }
  ":screen-home"
  ":feature-google-drive"
  ":screen-abc"
  ":feature-xyz"
}
app: ":app" {
  "App monolith shipped via GitHub Releases"
  "Wires the implementation of all screens"
}

ratio-data -> ratio-base
ratio-domain -> ratio-data
ratio-domain -> ratio-base

ratio-design -> ratio-res
ratio-nav -> ratio-domain
ratio-nav -> ratio-design

ratio-common-ui -> ratio-nav

screens -> ratio-common-ui
screens -> ratio-nav
screens -> ratio-res

app -> screens
