name: PR description check

on:
  pull_request:

permissions:
  contents: read

jobs:
  pr-description-check:
    name: PR description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Extract PR description (base 64)
        id: extract_description
        run: echo "PR_DESCRIPTION=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH | base64 | tr -d '\n')" >> $GITHUB_ENV

      - name: Run PR Description Check
        run: ./gradlew :ci-actions:pr-description-check:run --args="${{ env.PR_DESCRIPTION }}"