name: PR description check

on:
  pull_request:

permissions:
  contents: read

jobs:
  pr-description-check:
    name: PR description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Java
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4

      - name: Extract PR description (base 64)
        id: extract_description
        run: echo "PR_DESCRIPTION=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH | base64 | tr -d '\n')" >> $GITHUB_ENV

      - name: Run PR Description Check
        run: ./gradlew :ci-actions:pr-description-check:run --args="${{ env.PR_DESCRIPTION }}"