name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Java SDK
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

#  code_coverage:
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout GIT
#        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
#
#      - name: Setup Java SDK
#        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#
#      - name: Enable Gradle Wrapper caching (optimization)
#        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      - name: Code Coverage
#        run: ./gradlew koverHtmlReport
#
#      - name: Upload Code Coverage report
#        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
#        with:
#          name: code-coverage-report
#          path: app/build/artifacts/reports/kover/coverageResults/*
