name: Version bump

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Set up Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update version in libs.versions.toml
        id: update_version
        run: |
          VERSION_FILE="gradle/libs.versions.toml"
          CURRENT_DATE=$(date +'%Y.%m.%d')
          VERSION_CODE=$(grep 'version-code =' $VERSION_FILE | awk -F'=' '{print $2}' | tr -d ' "')
          NEW_VERSION_CODE=$((VERSION_CODE + 1))
          
          sed -i "s/version-name = \".*\"/version-name = \"$CURRENT_DATE\"/" $VERSION_FILE
          sed -i "s/version-code = \".*\"/version-code = \"$NEW_VERSION_CODE\"/" $VERSION_FILE
          
          echo "NEW_VERSION_NAME=$CURRENT_DATE" >> $GITHUB_ENV
          echo "NEW_VERSION_CODE=$NEW_VERSION_CODE" >> $GITHUB_ENV

      - name: Set branch name
        id: set_branch_name
        run: |
          BRANCH_NAME="version-bump-$(date +'%Y%m%d%H%M%S')"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Version bump: v${{ env.NEW_VERSION_NAME }} (${{ env.NEW_VERSION_CODE }})"
          base: "main"
          branch: ${{ env.BRANCH_NAME }}
          title: "Version bump: v${{ env.NEW_VERSION_NAME }} (${{ env.NEW_VERSION_CODE }})"
          body: "This PR updates the version-name to v${{ env.NEW_VERSION_NAME }} and increments the version-code to ${{ env.NEW_VERSION_CODE }}. Merge it when you want to cut a GitHub release (run the Release workflow manually afterwards)."
          labels: auto-update
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          delete-branch: true