name: Gradle wrapper validation

on:
  push:
    branches:
      - main
    paths:
      - 'gradle/wrapper/**'
      - 'gradlew'
      - 'gradlew.bat'
  pull_request:
    paths:
      - 'gradle/wrapper/**'
      - 'gradlew'
      - 'gradlew.bat'

permissions:
  contents: read

jobs:
  validation:
    name: Gradle wrapper validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@ed408507eac070d1f99cc633dbcf757c94c7933a # v4
