name: Gradle wrapper validation

on:
  push:
    branches:
      - main
    paths:
      - 'gradle/wrapper/**'
      - 'gradlew'
      - 'gradlew.bat'
  pull_request:
    paths:
      - 'gradle/wrapper/**'
      - 'gradlew'
      - 'gradlew.bat'

permissions:
  contents: read

jobs:
  validation:
    name: Gradle wrapper validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
